all:
  vars:
    control_plane_endpoint: 192.168.2.210
    load_balancer_ip_pool:
      - 192.168.2.224/27
metal:
  children:
    masters:
      hosts:
        metal0:
          {
            ansible_host: 192.168.2.154,
            mac: "52:54:00:21:eb:34",
            disk: sda,
            network_interface: enp1s0,
          }
        metal1:
          {
            ansible_host: 192.168.2.155,
            mac: "52:54:00:51:91:d7",
            disk: sda,
            network_interface: enp1s0,
          }
        metal2:
          {
            ansible_host: 192.168.2.156,
            mac: "52:54:00:56:8e:ca",
            disk: sda,
            network_interface: enp1s0,
          }
    workers:
      hosts:
        metal3:
          {
            ansible_host: 192.168.2.214,
            mac: "52:54:00:20:24:ad",
            disk: vda,
            network_interface: enp1s0,
          }
